// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetAssignment.Models;

#nullable disable

namespace dotnetAssignment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202095628_PhotoPathColumn")]
    partial class PhotoPathColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnetAssignment.Models.TouristPlace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tourists");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Cox's Bazar",
                            Name = "Cox bazar Sea Beach",
                            Rating = 3.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Khulna",
                            Name = "SundarBan",
                            Rating = 4.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Lalbag",
                            Name = "Lalbag Fort",
                            Rating = 3.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Cumilla",
                            Name = "Mohasthan Gor",
                            Rating = 4.2000000000000002,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
